#!/bin/bash
#Cogemos el archivo de configuracion de los puertos que deseamos
arcPuerto="etc/apache2/ports.conf"

#introducimos en el archivo de configuracion
cadPuerto="Listen $1"
#Buscar si ya existe
if [[grep -Fxq "$cadPuerto" "$arcPuerto"]]

then #Si existe
        echo "Puerto existe"
else #No existe
        echo "$cadPuerto" >> "$arcPuerto"
        echo "Puerto añadido: $1."
fi
