#!/bin/bash
#Cogemos el archivo de configuracion de los puertos que deseamos
arcPuerto="etc/apache2/ports.conf"

echo "Introduce el puerto que quieras añadir: "
#read del puerto a añadir
read puerto
#introducimos en el archivo de configuracion
cadPuerto="Listen $puerto"
#Buscar si ya existe
if [[grep -Fxq "$cadPuerto" "$arcPuerto"]]

then #Si existe
        echo "Puerto existe"
else #No existe
        echo "$cadenaPuerto" >> "$archivoPuerto"
        echo "Puerto añadido: $puerto."
fi
